### ISSUE TITLE
How to compile the code?

### ISSUE THREAD

**Issue by nilsmelchert** [jkevin1/OptiX#1]
Hi,
I am very new to Optix and I am trying to use your code as a template for my project. Could you tell me how you compiled your Project? There seem to be no CMakelist.txt files available. 
Are you able to set up you code to get it to work in an IDE like eclipse?

Cheers
Nils

**Comment by jkevin1** [comment]
Hi Nils,

The project is set up in visual studio, and should work if you have the dependencies installed.  This will only work on windows, I have not run it on any other platforms.  You might need to set up a developer account to get access to the OptiX runtime.

I recommend looking into [DXR](https://blogs.msdn.microsoft.com/directx/2018/03/19/announcing-microsoft-directx-raytracing/) which was just announced recently at GDC.  It should allow for faster ray/path tracing via hardware acceleration in the future.

Thanks,
Kevin
